import React from 'react'

export default function Video_editor() {
  return (
    <div>
      <h1>hello i am video editor feature</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim, hic rem nemo perspiciatis voluptate mollitia beatae unde? Perspiciatis mollitia id soluta dolores suscipit, architecto expedita dolorum distinctio amet modi aliquam accusantium sit dolorem ratione, aliquid numquam non autem. A corrupti repudiandae distinctio similique cumque, earum dolor voluptate error nam labore in nemo odio deleniti esse accusantium beatae itaque? Itaque beatae quia quis doloribus quos quae, rerum veniam necessitatibus numquam! Consectetur qui doloremque sed aut nostrum ex? Dolore laboriosam voluptate saepe temporibus voluptatibus dolorum, quae blanditiis quam laudantium tenetur? A, non? Fuga rerum harum amet voluptate tempore eos perferendis iure dignissimos nulla cum hic, maiores ratione in accusantium! Perferendis voluptate eveniet vel sit ducimus officiis nihil obcaecati explicabo, id, aliquid qui maxime dolore impedit quo ipsam at. Quis impedit ducimus eveniet iste voluptas nisi dolorum corporis officia, alias error dicta, eligendi similique tenetur possimus iure neque recusandae molestiae perspiciatis doloribus cumque corrupti! Repudiandae recusandae nemo alias ratione dicta perspiciatis id necessitatibus, qui laboriosam inventore. Incidunt tenetur perspiciatis iusto officiis fuga sunt vero perferendis laudantium, explicabo rem porro quidem provident reiciendis dolores molestias voluptate esse ex, quasi culpa? Error eligendi sunt odit odio, ullam minus dolorum pariatur itaque harum ea architecto eius sit labore quo molestiae autem accusamus natus fugit at incidunt. In nam dolorem quibusdam repellat cum ipsa voluptas optio at mollitia velit ratione laudantium ducimus aut aliquam nobis nisi culpa soluta, quod necessitatibus alias quisquam asperiores expedita atque. Rem distinctio doloribus ipsa, libero vel mollitia harum? Aliquid mollitia tempore vero aliquam? Possimus maiores recusandae maxime velit, quisquam excepturi quibusdam perspiciatis delectus dolorem quae harum molestiae, assumenda eligendi corrupti fugiat illo sit praesentium rerum amet? Neque voluptate asperiores enim quas aliquam corrupti, totam magni aperiam sint unde laboriosam impedit provident, quaerat modi, facere temporibus cumque illum id porro. Ea a aliquid sint deleniti aut placeat animi eaque soluta consequuntur, rem amet adipisci, porro iure voluptatibus? Quo dolorem distinctio minus, quasi, fuga rerum porro incidunt, temporibus eveniet quam hic sint accusamus natus libero cumque totam reiciendis facilis est? Quia cupiditate accusantium optio quibusdam doloremque et earum quidem est mollitia. Vel deleniti officia quibusdam neque aperiam asperiores corporis quas magnam dolorum quasi alias ipsam sequi, esse totam nesciunt at sint? Iure error quidem porro obcaecati et exercitationem adipisci. Atque quis nemo optio corporis sapiente nobis officia, ipsam exercitationem adipisci modi pariatur maxime nisi expedita ullam repellat esse odit, voluptas voluptatibus dolorem. Atque, rem.</p>
    </div>
  )
}
